# Generated by Django 2.2.2 on 2020-01-02 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('fullname', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(editable=False)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(max_length=20)),
                ('x_axis', models.CharField(max_length=64)),
                ('y_axis', models.CharField(max_length=64)),
                ('chart_style', models.CharField(blank=True, max_length=20)),
                ('create_time', models.DateTimeField(editable=False)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to='Server.User')),
            ],
        ),
    ]
