# Generated by Django 2.2.2 on 2020-01-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0003_auto_20200103_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='label',
        ),
        migrations.AddField(
            model_name='chart',
            name='y_axis',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
